<?php

namespace AppBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;

class CursoAdminController extends CRUDController
{
    public function createAction()
    {
        try{
            return parent::createAction(); // TODO: Change the autogenerated stub
        }catch (\Exception $e)
        {
            $this->addFlash('sonata_flash_error', 'Já existe um curso com este NOME.');
            return new RedirectResponse(
                $this->admin->generateUrl('create', array('filter' => $this->admin->getFilterParameters()))
            );
        }
    }

    public function editAction()
    {
        try{
            return parent::createAction(); // TODO: Change the autogenerated stub
        }catch (\Exception $e)
        {
            $this->addFlash('sonata_flash_error', 'Já existe um curso com este NOME.');
            return new RedirectResponse(
                $this->admin->generateUrl('create', array('filter' => $this->admin->getFilterParameters()))
            );
        }

    }
}
