app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix: /resetting
