<?php

namespace AppBundle\Admin;

use AppBundle\Entity\Curso;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class CursoAdmin extends AbstractAdmin
{
    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')
            ->add('nomeCurso')
            ->add('codigoCurso')
            ->add('tipoCurso')
            ->add('isActive')
        ;
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('id')
            ->add('nomeCurso')
            ->add('codigoCurso')
            ->add('isActive')
            ->add('_action', null, array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                    'delete' => array(),
                ),
            ))
        ;
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('nomeCurso')
            ->add('areaCurso')
            ->add('modalidadeCurso')
            ->add('tipoCurso')

        ;
    }

    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')
            ->add('nomeCurso')
            ->add('codigoCurso')
            ->add('isActive')
        ;
    }

    public function prePersist($object)
    {
        $object->setCodigoCurso("{$object->getModalidadeCurso()->getId()}{$object->getTipoCurso()->getId()}{$object->getAreaCurso()->getId()}");
        //$object->codigoCurso = $object->modalidadeCurso.$object->tipoCurso.$object->areaCurso;
        parent::prePersist($object); // TODO: Change the autogenerated stub
    }

    public function postPersist($object)
    {
        $object->setCodigoCurso("{$object->getCodigoCurso()}{$object->getId()}");
        $em = $this->getModelManager();
        $em->update($object);
        parent::postPersist($object); // TODO: Change the autogenerated stub
    }

}
